USE [DCMS]
GO
/****** Object:  Table [dbo].[APPOINTMENT]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPOINTMENT](
	[ID] [int] NOT NULL,
	[LOCATION_ID] [int] NULL,
	[APPOINTMENT_ID] [int] NOT NULL,
	[DOCTER_ID] [int] NULL,
	[PATIENT_ID] [int] NULL,
	[TIME] [time](7) NULL,
	[DATE] [date] NULL,
	[FEE] [money] NULL,
	[PATIENT_HISTORY] [nvarchar](max) NULL,
	[PRESCRIPTION] [nvarchar](max) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_APPOINTMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DOCTOR]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DOCTOR](
	[ID] [int] NOT NULL,
	[LOCATION_ID] [int] NULL,
	[NAME] [varchar](50) NULL,
	[FNAME] [varchar](50) NULL,
	[AGE] [int] NULL,
	[JOINING_DATE] [datetime] NULL,
	[CNIC] [nvarchar](50) NULL,
	[QUALIFICATION] [nvarchar](100) NULL,
	[DESIGNATION] [nvarchar](50) NULL,
	[TELEPHONE_NUM] [varchar](50) NULL,
	[CITY] [varchar](50) NULL,
	[MOBILE_NUM] [varchar](50) NULL,
	[ACTIVE] [varchar](1) NULL,
	[REMARK] [nvarchar](max) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_Docter] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DOCTOR_FACULITY]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOCTOR_FACULITY](
	[ID] [int] NOT NULL,
	[LOCATION_ID] [int] NULL,
	[DOCTOR_ID] [int] NULL,
	[FACULITY_ID] [int] NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_DOCTOR_FACULITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[FACULITY]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACULITY](
	[ID] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
	[STATUS] [nvarchar](1) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_FIELD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LEAVE]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LEAVE](
	[ID] [int] NOT NULL,
	[LOCATION_ID] [int] NULL,
	[DOCTOR_ID] [int] NULL,
	[LEAVE_FROM] [date] NULL,
	[LEAVE_TO] [date] NULL,
	[ACTIVE] [varchar](1) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_LEAVE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOCATION]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCATION](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](250) NULL,
	[CONTACT_1] [varchar](50) NULL,
	[CONTACT_2] [varchar](50) NULL,
	[CONTACT_3] [varchar](50) NULL,
	[FAX_NO] [varchar](50) NULL,
	[CITY] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_LOCATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORGANIZATION]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORGANIZATION](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](250) NULL,
	[CONTACT_1] [varchar](50) NULL,
	[CONTACT_2] [varchar](50) NULL,
	[CONTACT_3] [varchar](50) NULL,
	[FAX_NO] [varchar](50) NULL,
	[COUNTRY] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ORGANIZATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PATIENT]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PATIENT](
	[ID] [int] NOT NULL,
	[LOCATION_ID] [int] NULL,
	[NAME] [varchar](50) NULL,
	[FNAME] [varchar](50) NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[AGE] [int] NULL,
	[CNIC] [nvarchar](50) NULL,
	[GENDER] [varchar](1) NULL,
	[MOBILE_NUM] [varchar](50) NULL,
	[CITY] [varchar](50) NULL,
	[TELEPHONE_NUM] [varchar](50) NULL,
	[REMARKS] [nvarchar](max) NULL,
	[ACTIVE] [varchar](1) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_PATIENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SCHEDULE]    Script Date: 11/7/2017 10:23:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHEDULE](
	[ID] [int] NOT NULL,
	[LOCATION_ID] [int] NULL,
	[DOCTOR_ID] [int] NULL,
	[DAY] [nvarchar](50) NULL,
	[TIME_FROM] [time](7) NULL,
	[TIME_TO] [time](7) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_USER] [nvarchar](50) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_USER] [nvarchar](50) NULL,
 CONSTRAINT [PK_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
INSERT [dbo].[FACULITY] ([ID], [NAME], [STATUS], [CREATED_ON], [CREATED_USER], [MODIFIED_ON], [MODIFIED_USER]) VALUES (1, N'Dentist', N'Y', CAST(0x0000A82400000000 AS DateTime), N'AHSAN', NULL, NULL)
GO
INSERT [dbo].[FACULITY] ([ID], [NAME], [STATUS], [CREATED_ON], [CREATED_USER], [MODIFIED_ON], [MODIFIED_USER]) VALUES (2, N'Eye', N'Y', CAST(0x0000A82400000000 AS DateTime), N'AHSAN', NULL, NULL)
GO
INSERT [dbo].[FACULITY] ([ID], [NAME], [STATUS], [CREATED_ON], [CREATED_USER], [MODIFIED_ON], [MODIFIED_USER]) VALUES (3, N'Orthopadict', N'Y', CAST(0x0000A82400000000 AS DateTime), N'AHSAN', NULL, NULL)
GO
ALTER TABLE [dbo].[APPOINTMENT]  WITH CHECK ADD  CONSTRAINT [FK_APPOINTMENT_DOCTOR] FOREIGN KEY([DOCTER_ID])
REFERENCES [dbo].[DOCTOR] ([ID])
GO
ALTER TABLE [dbo].[APPOINTMENT] CHECK CONSTRAINT [FK_APPOINTMENT_DOCTOR]
GO
ALTER TABLE [dbo].[APPOINTMENT]  WITH CHECK ADD  CONSTRAINT [FK_APPOINTMENT_LOCATION] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATION] ([ID])
GO
ALTER TABLE [dbo].[APPOINTMENT] CHECK CONSTRAINT [FK_APPOINTMENT_LOCATION]
GO
ALTER TABLE [dbo].[APPOINTMENT]  WITH CHECK ADD  CONSTRAINT [FK_APPOINTMENT_PATIENT] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[PATIENT] ([ID])
GO
ALTER TABLE [dbo].[APPOINTMENT] CHECK CONSTRAINT [FK_APPOINTMENT_PATIENT]
GO
ALTER TABLE [dbo].[DOCTOR]  WITH CHECK ADD  CONSTRAINT [FK_DOCTOR_LOCATION] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATION] ([ID])
GO
ALTER TABLE [dbo].[DOCTOR] CHECK CONSTRAINT [FK_DOCTOR_LOCATION]
GO
ALTER TABLE [dbo].[DOCTOR_FACULITY]  WITH CHECK ADD  CONSTRAINT [FK_DOCTOR_FACULITY_LOCATION] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATION] ([ID])
GO
ALTER TABLE [dbo].[DOCTOR_FACULITY] CHECK CONSTRAINT [FK_DOCTOR_FACULITY_LOCATION]
GO
ALTER TABLE [dbo].[LEAVE]  WITH CHECK ADD  CONSTRAINT [FK_LEAVE_DOCTOR] FOREIGN KEY([DOCTOR_ID])
REFERENCES [dbo].[DOCTOR] ([ID])
GO
ALTER TABLE [dbo].[LEAVE] CHECK CONSTRAINT [FK_LEAVE_DOCTOR]
GO
ALTER TABLE [dbo].[LEAVE]  WITH CHECK ADD  CONSTRAINT [FK_LEAVE_LOCATION] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATION] ([ID])
GO
ALTER TABLE [dbo].[LEAVE] CHECK CONSTRAINT [FK_LEAVE_LOCATION]
GO
ALTER TABLE [dbo].[PATIENT]  WITH CHECK ADD  CONSTRAINT [FK_PATIENT_LOCATION] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATION] ([ID])
GO
ALTER TABLE [dbo].[PATIENT] CHECK CONSTRAINT [FK_PATIENT_LOCATION]
GO
ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_DOCTOR] FOREIGN KEY([DOCTOR_ID])
REFERENCES [dbo].[DOCTOR] ([ID])
GO
ALTER TABLE [dbo].[SCHEDULE] CHECK CONSTRAINT [FK_SCHEDULE_DOCTOR]
GO
ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_LOCATION] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATION] ([ID])
GO
ALTER TABLE [dbo].[SCHEDULE] CHECK CONSTRAINT [FK_SCHEDULE_LOCATION]
GO
